package com.inspiredandroid.kai.ui.chat

import androidx.compose.runtime.Immutable
import io.github.vinceglb.filekit.PlatformFile

@Immutable
data class ChatActions(
    val ask: (String) -> Unit,
    val toggleSpeechOutput: () -> Unit,
    val retry: () -> Unit,
    val clearHistory: () -> Unit,
    val setIsSpeaking: (Boolean, String) -> Unit,
    val addFile: (PlatformFile) -> Unit,
    val removeFile: (PlatformFile) -> Unit,
    val startNewChat: () -> Unit,
    val regenerate: () -> Unit,
    val cancel: () -> Unit,
    val selectService: (String) -> Unit,
    val selectModel: (String, String) -> Unit,
    val loadConversation: (String) -> Unit,
    val deleteConversation: (String) -> Unit,
    val clearUnreadHeartbeat: () -> Unit,
    val clearSnackbar: () -> Unit,
    val undoDeleteConversation: () -> Unit,
    val submitUiCallback: (event: String, data: Map<String, String>) -> Unit,
    val resubmit: (messageId: String, event: String, data: Map<String, String>) -> Unit,
    val enterInteractiveMode: () -> Unit,
    val exitInteractiveMode: () -> Unit,
    val goBackInteractiveMode: () -> Unit,
    val sendSmsDraft: (String) -> Unit,
    val discardSmsDraft: (String) -> Unit,
    // 协作模式
    val openCollaborationWizard: () -> Unit,
    val dismissCollaborationWizard: () -> Unit,
    val startCollaborationTask: (com.inspiredandroid.kai.data.collaboration.CollaborationWizardParams) -> Unit,
    val stopCollaboration: () -> Unit,
    val clearCollaborationNotification: () -> Unit,
    val openCollaborationModelView: (String) -> Unit,
    val closeCollaborationModelView: () -> Unit,
    val openHistoryFolder: (String) -> Unit,
    val closeHistoryFolder: () -> Unit,
    val closeHistoryTreeSheet: () -> Unit,
    val copyConversationBranch: (String, Int) -> Unit,
    val clearPendingCopyText: () -> Unit,
    val retryCollaborationModel: (String) -> Unit,
    val retryCollaborationTask: (String) -> Unit,
    val setCollaborationModelScore: (String, Double) -> Unit,
    val navigateCollaborationModel: (Int) -> Unit,
    // 战争模式
    val openWarWizard: () -> Unit,
    val dismissWarWizard: () -> Unit,
    val startWarTask: (com.inspiredandroid.kai.data.war.WarWizardParams) -> Unit,
    val stopWar: () -> Unit,
    val clearWarNotification: () -> Unit,
    val openWarResultView: (String) -> Unit,
    val closeWarResultView: () -> Unit,
    val copyPlainText: (String) -> Unit,
    val optimizePrompt: (String) -> Unit,
    val clearPendingPromptText: () -> Unit,
    /** 用户消息“重新发送”：截断到该消息之前，再以原文重新提问。 */
    val resendUserMessage: (messageId: String, text: String) -> Unit,
)
